package common

// EncryptionKeyAction enum to describe the encryption key action
type EncryptionKeyAction int64

const (
	// Length of the encryption key generated by the application at first run
	EncryptionKeyLength   = 256
	CONFIG_ENCRYPTION_KEY = "encryption_key"

	EncryptionKeyAction_Generate EncryptionKeyAction = iota
	EncryptionKeyAction_Decrypt
	EncryptionKeyAction_Encrypt
	EncryptionKeyAction_Verify
)
